// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8HJdn0m0q2sGONSVW7AyxRYd20QZdBXI',
    appId: '1:492845323290:web:309fc0f1c2443d9558ada3',
    messagingSenderId: '492845323290',
    projectId: 'dbuddy-97725',
    authDomain: 'dbuddy-97725.firebaseapp.com',
    storageBucket: 'dbuddy-97725.firebasestorage.app',
    measurementId: 'G-Y1VSWMT3NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9aXYKwL0Qtz_QDs2UgMk_hjZoqxXwQbo',
    appId: '1:492845323290:android:6c1b45d9e3071e2758ada3',
    messagingSenderId: '492845323290',
    projectId: 'dbuddy-97725',
    storageBucket: 'dbuddy-97725.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmu9YmQ_68JCJh34ZXhXFuzhWt-s8v8uw',
    appId: '1:492845323290:ios:3258099aa788951958ada3',
    messagingSenderId: '492845323290',
    projectId: 'dbuddy-97725',
    storageBucket: 'dbuddy-97725.firebasestorage.app',
    iosBundleId: 'com.example.dbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmu9YmQ_68JCJh34ZXhXFuzhWt-s8v8uw',
    appId: '1:492845323290:ios:3258099aa788951958ada3',
    messagingSenderId: '492845323290',
    projectId: 'dbuddy-97725',
    storageBucket: 'dbuddy-97725.firebasestorage.app',
    iosBundleId: 'com.example.dbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8HJdn0m0q2sGONSVW7AyxRYd20QZdBXI',
    appId: '1:492845323290:web:ecb606e69a1affaa58ada3',
    messagingSenderId: '492845323290',
    projectId: 'dbuddy-97725',
    authDomain: 'dbuddy-97725.firebaseapp.com',
    storageBucket: 'dbuddy-97725.firebasestorage.app',
    measurementId: 'G-RPGGQYE8F0',
  );
}
